### ISSUE TITLE
Cannot find Recidivism dataset implementation?

### ISSUE THREAD

**Issue by qslim** [yushundong/PyGDebias#13]
Nice project!
Is Recidivism implemented? I cannot find it. Please show me the position if it does exist.

Thanks!

**Comment by yushundong** [comment]
Hi, thanks for reaching out!

Recidivism dataset is named as Bail in PyGDebias, and you may find an example of importing and using Bail (i.e., Recidivism) dataset in folder *examples*. It automatically downloads everything needed.

**Comment by qslim** [comment]
Thanks!
