### ISSUE TITLE
Bail Results using FairGNN

### ISSUE THREAD

**Issue by joyce2363** [yushundong/PyGDebias#2]
Curious about what hyper-parameters were used to obtain the results in section 7 for the Bail dataset using FairGNN?

**Comment by yushundong** [comment]
Hi,

Thanks for your interest in our work!

I tried to use our hyper-parameters on the example you provided in the email directly, and I have the following results:

Best Epoch: 475
Total time elapsed: 23.9954s
ACC: 0.9095147276965458
AUCROC:  0.8919544544544546
F1:  0.9095147276965458
ACC_sens0: 0.9079461571862788
AUCROC_sens0:  0.8981642897978682
F1_sens0:  0.9079461571862788
ACC_sens1:  0.9110099337748344
AUCROC_sens1:  0.8835607053048442
F1_sens1:  0.9110099337748344
SP:  0.07909726875109635
EO: 0.05534965301609085

You may find your example under our hyper-parameter configurations here:

https://drive.google.com/drive/folders/1qP-FWT8DpRyEu0TrTh5v8tWv7EBFxWrU?usp=sharing

Thanks!

Best,
Yushun
